# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KosolapovNikita' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KosolapovNikita
  
  pod 'Alamofire', '~> 5.1'
  # Pods for KosolapovNikita
  
  pod 'SwiftKeychainWrapper', '~> 3.4'
  
  pod 'RealmSwift'
  
  pod 'Firebase/Database'
  pod 'Firebase/Core'

end
